import { app, BrowserWindow, ipcMain, protocol } from 'electron';
import fontkit from 'fontkit';
import glob from 'glob';
import url from 'url';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.whenReady().then(() => {
  protocol.registerFileProtocol('font', (request, callback) => {
    const filePath = url.fileURLToPath('file://' + request.url.slice('font://'.length));
    callback(filePath);
  });
});

//// realized I didn't really need this, but don't want to lose it in case I want it back
//// import { app, session } from 'electron';
//// import { PathLike, readdirSync } from 'fs';
//// import path from 'path';
// if (process.platform == 'win32') {
//   const appDataPath = process.env.APPDATA;
//   const reactDevToolsPath = '..\\Local\\Google\\Chrome\\User Data\\Default\\Extensions\\fmkadmapgofadopljbjfkapdkoienihi';
//   const extensionPath = path.join(appDataPath, reactDevToolsPath);
//   const versionPath = readdirSync(extensionPath, {withFileTypes: true}).filter(x => x.isDirectory()).map(y => y.name)[0];
//   app.whenReady().then(async () => await session.defaultSession.loadExtension(path.join(extensionPath, versionPath)));
// }

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
ipcMain.handle('font-families', async (): Promise<[string, Font[]][]> => await getFontFamilies());

class FontConstructor implements Font {
  file: string;
  fullName: string;
  subfamilyName: string;
  availableFeatures: string[];
  constructor(file: string, fullName: string, subfamilyName: string, availableFeatures: string[]) {
    this.file = file;
    this.fullName = fullName;
    this.subfamilyName = subfamilyName;
    this.availableFeatures = availableFeatures;
  }
}

function getSystemFontFolder(): string {
  const platform = process.platform;
  let folder: string;
  switch (platform) {
    case 'win32':
      folder = 'C:/Windows/Fonts';
      break;
    case 'darwin':
      folder = '$HOME/Library/Fonts';
      break;
    case 'linux':
      folder = '/usr/share/fonts';
      break;
    default:
      console.log(platform);
      folder = '';
  }
  return folder;
}

async function getFonts(): Promise<[string, fontkit.Font][]> {
  const fonts: [string, fontkit.Font][] = [];
  const folder = getSystemFontFolder();
  if (folder) {
    // not bothering with path.join since glob requires forward slashes anyway
    const paths = await glob(`${folder}/*.{ttf,otf,woff,woff2}`);
    await Promise.all(paths.map(async (element) => {
      try {
        const font = await fontkit.open(element);
        fonts.push([element, font]);
      }
      catch (e) {
        console.log(element);
        console.log(e);
      }
    }));
  }
  return fonts;
}

async function getFontFamilies(): Promise<[string, Font[]][]> {
  const fonts = await getFonts();
  const familiesMap: Map<string, Font[]> = new Map();
  fonts.forEach(element => {
    const filePath = element[0].replaceAll('\\', '/').trim();
    const font = element[1];
    if (!familiesMap.has(font.familyName)) {
      familiesMap.set(font.familyName, [])
    }
    const availableFeatures = [...new Set(font.availableFeatures)]; // remove duplicates
    familiesMap.get(font.familyName)?.push(new FontConstructor(filePath, font.fullName, font.subfamilyName, availableFeatures));
  });
  const families = Array.from(familiesMap.entries());
  families.sort((a, b) => a[0].localeCompare(b[0]));
  families.forEach(element => {
    const fonts = element[1];
    fonts.sort((a, b) => a.subfamilyName.localeCompare(b.subfamilyName));
    // always display regular style first
    fonts.forEach((font, index) => {
      if (font.subfamilyName == 'Regular') {
        fonts.splice(index, 1);
        fonts.unshift(font);
      }
    });
  });
  return families;
}
